#! /bin/sh

# Bench script arguments
# $1 is the benchmark to run
# $2 is the number of samples
# $3 is the number of warming run
# $4 is the number of seconds to sleep between benchmark
# $5 is boolean to record frequency
# $6 is boolean to record temperature

BENCHMARKS=${1:-"all"}
SAMPLE_COUNT=${2:-"100"}
WARMING_RUNS=${3:-"100"}
SLEEP_TIMES=${4:-"30"}
RECORD_FREQ=${5:-"#t"}
RECORD_TEMP=${6:-"#t"}

echo "Config:"
echo "Benchmarks: $BENCHMARKS"
echo "Sample counts: $SAMPLE_COUNT"
echo "Warming runs: $WARMING_RUNS"
echo "Sleep time: $SLEEP_TIMES"
echo "Record CPU frequency?: $RECORD_FREQ"
echo "Record CPU temperature?: $RECORD_TEMP"

echo "\nVerifying configuration"

if [ $RECORD_TEMP = "#t" ]; then
  sensors > /dev/null 2> /dev/null
  if [ ! "$?" = "0" ]; then
    echo "sensors command not working."
    echo "Try installing lm-sensors or disable temperature recording"
    exit;
  fi
fi

echo "Time: $(date): Started"

for warming in $WARMING_RUNS ; do

    for sleep in $SLEEP_TIMES ; do
        cmd="./bench $BENCHMARKS $SAMPLE_COUNT $warming $sleep $RECORD_FREQ $RECORD_TEMP"
        echo "Time: $(date): $cmd"
        $cmd
    done

done

echo "Time: $(date): Finished"
